import json
import os
import shutil

def generate_dacode_manifest():
    task_cfg_path = "task_cfg/dw.jsonl"
    eval_cfg_path = "eval_cfg/eval_dw.jsonl"
    manifest_path = "data/dacode_manifest.jsonl"
    
    # Load tasks
    tasks = {}
    with open(task_cfg_path, "r", encoding="utf-8") as f:
        for line in f:
            data = json.loads(line)
            tasks[data["id"]] = data["instruction"]
            
    # Load evals and merge
    manifest_tasks = []
    with open(eval_cfg_path, "r", encoding="utf-8") as f:
        for line in f:
            data = json.loads(line)
            task_id = data["id"]
            if task_id not in tasks:
                continue
                
            question = tasks[task_id]
            data_lake_dir = f"data/dacode_lake/source/{task_id}"
            
            # Generate test_code
            # Most DW tasks use compare_csv
            if "compare_csv" in data["func"]:
                files_to_check = []
                for res in data["result"]:
                    if "file" in res:
                        files_to_check.extend(res["file"])
                
                # Python test code to append
                test_code = f"""
import os
import pandas as pd

files_to_check = {files_to_check}
gold_dir = r"data/gold/gold/{task_id}"

for fname in files_to_check:
    assert os.path.exists(fname), f"File {{fname}} was not generated by your code!"
    expected_path = os.path.join(gold_dir, fname)
    
    actual_df = pd.read_csv(fname)
    expected_df = pd.read_csv(expected_path)
    
    assert actual_df.shape == expected_df.shape, f"Shape mismatch for {{fname}}: Expected {{expected_df.shape}}, got {{actual_df.shape}}"
    
    # Sort both by all columns to ignore order
    actual_sorted = actual_df.sort_values(by=actual_df.columns.tolist()).reset_index(drop=True)
    expected_sorted = expected_df.sort_values(by=expected_df.columns.tolist()).reset_index(drop=True)
    
    # Compare basic structure
    assert list(actual_sorted.columns) == list(expected_sorted.columns), f"Columns mismatch for {{fname}}"
    
print("All assertions passed!")
"""
            else:
                test_code = "print('Manual eval required')"
                
            manifest_tasks.append({
                "task_id": task_id,
                "question": question,
                "test_code": test_code,
                "data_lake_dir": data_lake_dir
            })
            
    with open(manifest_path, "w", encoding="utf-8") as f:
        for t in manifest_tasks:
            f.write(json.dumps(t) + "\n")
            
    print(f"Generated manifest {manifest_path} with {len(manifest_tasks)} tasks.")

if __name__ == "__main__":
    generate_dacode_manifest()
